M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Thu 08 Sep 2022 22:48:18 BST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-08T22:48:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X17.5Y-17.5
X17.5Y-143.5
X93.5Y-17.5
T2
X26.5Y-26.5
X26.5Y-75.5
X26.5Y-85.5
X26.5Y-134.5
X84.5Y-26.5
X84.5Y-75.5
X84.5Y-85.5
X84.5Y-134.5
T0
M30
